"""P2-002 Alembic migration tests.

Prove the single P2-002 revision exists, is a well-formed base revision that Alembic
can load, creates **only** the 8 approved core tables (no deferred table), uses
deterministic DEC-0005 naming, embeds no credential, and that Alembic's
``target_metadata`` (the shared ``Base.metadata``) includes those tables. No engine
is created and no database is contacted.
"""

import re
from pathlib import Path

from alembic.config import Config
from alembic.script import ScriptDirectory

from app.db import models  # noqa: F401  ensures the tables are registered
from app.db.base import Base

BACKEND_DIR = Path(__file__).resolve().parents[2]
ALEMBIC_INI = BACKEND_DIR / "alembic.ini"
ALEMBIC_DIR = BACKEND_DIR / "alembic"
MIGRATION = ALEMBIC_DIR / "versions" / "p2_002_core_domain_models.py"

CORE_TABLES = {
    "users",
    "songs",
    "audio_files",
    "separation_jobs",
    "tags",
    "song_tags",
    "usage_events",
    "daily_usage",
}
DEFERRED_TABLES = {
    "ratings",
    "coupons",
    "coupon_redemptions",
    "signed_url_grants",
    "content_reports",
    "admin_audit_events",
}


def _migration_text() -> str:
    return MIGRATION.read_text(encoding="utf-8")


def _created_tables(text: str) -> set[str]:
    return set(re.findall(r'op\.create_table\(\s*"([^"]+)"', text))


def test_migration_file_exists():
    assert MIGRATION.is_file()


def test_migration_creates_exactly_the_core_tables():
    assert _created_tables(_migration_text()) == CORE_TABLES


def test_migration_creates_no_deferred_tables():
    assert _created_tables(_migration_text()).isdisjoint(DEFERRED_TABLES)


def test_migration_is_the_base_revision_alembic_can_load():
    # Re-scoped by P3-001 (DEC-0010 §3): P2-002 is no longer the head, but it is
    # still the single base revision of one linear chain. The head assertion moved
    # to tests/db/test_auth_models.py, which owns the Phase 3 revision.
    script = ScriptDirectory.from_config(Config(str(ALEMBIC_INI)))
    revisions = {r.revision: r for r in script.walk_revisions()}
    assert "p2_002_core_domain_models" in revisions
    assert revisions["p2_002_core_domain_models"].down_revision is None
    assert len(script.get_heads()) == 1


def test_migration_uses_deterministic_convention_names():
    text = _migration_text()
    for name in (
        "pk_users",
        "pk_song_tags",
        "fk_songs_user_id_users",
        "fk_usage_events_separation_job_id_separation_jobs",
        "uq_users_email",
        "uq_usage_events_song_id",
        "uq_daily_usage_user_id",
        "ck_songs_status_allowed",
        "ck_separation_jobs_model_tier_allowed",
        "ix_songs_user_id",
        "ix_daily_usage_usage_date",
    ):
        assert name in text, f"missing deterministic name: {name}"
    # No PostgreSQL-autogenerated constraint names (e.g. "<table>_pkey").
    assert "_pkey" not in text


def test_migration_embeds_no_credentials_or_url():
    text = _migration_text().lower()
    assert "://" not in text
    assert "password" not in text
    assert "database_url" not in text


def test_target_metadata_includes_the_core_tables():
    # env.py sets target_metadata = Base.metadata; importing app.db registers the
    # tables, so Alembic autogenerate/upgrade sees exactly these.
    assert CORE_TABLES <= set(Base.metadata.tables)
